// Generated by ReScript, PLEASE EDIT WITH CARE

import Ava from "ava";
import * as Stripe from "../src/Stripe.res.mjs";

Ava("Calculate past usage", t => {
  t.deepEqual(Stripe.Billing.calculatePastUsageBill(100, new Date("2025-01-01"), new Date("2025-01-01"), "month"), 0);
  t.deepEqual(Stripe.Billing.calculatePastUsageBill(100, new Date("2025-01-01"), new Date("2025-02-01"), "month"), 100);
  t.deepEqual(Stripe.Billing.calculatePastUsageBill(100, new Date("2025-01-01"), new Date("2025-03-01"), "month"), 200);
  t.deepEqual(Stripe.Billing.calculatePastUsageBill(100, new Date("2025-01-01"), new Date("2025-01-15"), "month"), 45);
});

/*  Not a pure module */
